### ISSUE TITLE
增加语言选项 Add a language option

### ISSUE THREAD

**Issue by EricZhou05** [Danmaku-Kakashi/Danmaku-Kakashi-Ext#4]
非常感谢大佬开发~考虑到在油管观看中文弹幕的用户为国人居多，插件增加中文语言切换选项会不会更好呢？

Thank you so much for developing this! Since most users who watch Chinese bullet chat on YouTube are likely Chinese, wouldn't it be better to add a Chinese language switch option to the plugin?

**Comment by ErlanLiang** [comment]
谢谢 我们会在下一个更新加入语言切换选项，目前我们并没有根据用户Chrome语言进行切换。目前切换语言的方式是在官网登录之后选择中文，之后插件的语言设置就会同步成中文 :) 谢谢支持

Thank you. We will add the language-switching option in the next update. Currently, we do not switch based on the user's Chrome language. The current way to switch the language is to select Chinese after logging in to the official website, and then the language setting of the plug-in will be synchronized to Chinese :) Thank you for your support!

**Comment by mgrddsj** [comment]
已在 v1.0.2 版本中修复：https://github.com/Danmaku-Kakashi/Danmaku-Kakashi-Ext/releases/tag/v1.0.2

Fixed in Release v1.0.2: https://github.com/Danmaku-Kakashi/Danmaku-Kakashi-Ext/releases/tag/v1.0.2
